# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6312c91ae819849f625f4e8b05a939fdd8d4a9ba27f38d7c952ae91107b828baa485ec3f3436a941c639534253eeb9957e609e068d9299bb1c54e881ed58a64f

test:
  secret_key_base: d10117f9bd860719dd93a9cebbb14e2a6eeef1988b69577a8c0d5cbc136427b663305b55492913d37aa9d0e4a701ec8bc2fb78aff3245490c200a767fab47674

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
